name = "fun-box-mobile"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[env.production]
name = "fun-box-mobile"

[env.staging]
name = "fun-box-mobile-staging"

# 环境变量
[env.production.vars]
VITE_API_URL = "https://fun-box-admin.pages.dev"

[env.staging.vars]
VITE_API_URL = "https://fun-box-admin-staging.pages.dev"
