# Cloudflare配置文件

# 客户移动端配置
[[pages]]
name = "comic-mobile"
source = "apps/mobile-client"
build_dir = "dist"
compatibility_date = "2024-01-01"

# 后台管理端+服务端配置
[[pages]]
name = "comic-admin"
source = "apps/admin-server"
build_dir = "build/client"
functions_dir = "build/server"
compatibility_date = "2024-01-01"

# 环境变量配置
[env.production.vars]
NODE_ENV = "production"
DATABASE_URL = ""
JWT_SECRET = ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""

[env.staging.vars]
NODE_ENV = "staging"
DATABASE_URL = ""
JWT_SECRET = ""

# KV存储配置
[[env.production.kv_namespaces]]
binding = "CACHE"
id = ""

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = ""

# D1数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "comic-prod"
database_id = ""

# R2存储配置
[[env.production.r2_buckets]]
binding = "FILES"
bucket_name = "comic-files"

# 开发环境配置
[[env.development.kv_namespaces]]
binding = "CACHE"
id = ""

[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = ""

[[env.development.d1_databases]]
binding = "DB"
database_name = "comic-dev"
database_id = ""

[[env.development.r2_buckets]]
binding = "FILES"
bucket_name = "comic-files-dev"
