// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/comics": {
    params: {};
  };
  "/admin/comics/:id/chapters": {
    params: {
      "id": string;
    };
  };
  "/admin/comics/:id/chapters/:chapterId/pages": {
    params: {
      "id": string;
      "chapterId": string;
    };
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/auth": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/api/comics": {
    params: {};
  };
  "/api/comics/:id": {
    params: {
      "id": string;
    };
  };
  "/api/chapters/:id": {
    params: {
      "id": string;
    };
  };
  "/api/users": {
    params: {};
  };
  "/api/upload": {
    params: {};
  };
  "/api/auth": {
    params: {};
  };
  "/api/purchase": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/favicon.ico" | "/admin/login" | "/admin/dashboard" | "/admin/comics" | "/admin/comics/:id/chapters" | "/admin/comics/:id/chapters/:chapterId/pages" | "/admin/categories" | "/admin/users" | "/admin/analytics" | "/admin/auth" | "/admin/orders" | "/admin/settings" | "/api/comics" | "/api/comics/:id" | "/api/chapters/:id" | "/api/users" | "/api/upload" | "/api/auth" | "/api/purchase";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/favicon.ts": {
    id: "routes/favicon";
    page: "/favicon.ico";
  };
  "routes/admin/login.tsx": {
    id: "routes/admin/login";
    page: "/admin/login";
  };
  "components/admin/AdminLayout.tsx": {
    id: "components/admin/AdminLayout";
    page: "/admin/dashboard" | "/admin/comics" | "/admin/comics/:id/chapters" | "/admin/comics/:id/chapters/:chapterId/pages" | "/admin/categories" | "/admin/users" | "/admin/analytics" | "/admin/auth" | "/admin/orders" | "/admin/settings";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/comics.tsx": {
    id: "routes/admin/comics";
    page: "/admin/comics";
  };
  "routes/admin/comics.$id.chapters.tsx": {
    id: "routes/admin/comics.$id.chapters";
    page: "/admin/comics/:id/chapters";
  };
  "routes/admin/comics.$id.chapters.$chapterId.pages.tsx": {
    id: "routes/admin/comics.$id.chapters.$chapterId.pages";
    page: "/admin/comics/:id/chapters/:chapterId/pages";
  };
  "routes/admin/categories.tsx": {
    id: "routes/admin/categories";
    page: "/admin/categories";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/analytics.tsx": {
    id: "routes/admin/analytics";
    page: "/admin/analytics";
  };
  "routes/admin/auth.tsx": {
    id: "routes/admin/auth";
    page: "/admin/auth";
  };
  "routes/admin/orders.tsx": {
    id: "routes/admin/orders";
    page: "/admin/orders";
  };
  "routes/admin/settings.tsx": {
    id: "routes/admin/settings";
    page: "/admin/settings";
  };
  "routes/api/comics.ts": {
    id: "routes/api/comics";
    page: "/api/comics";
  };
  "routes/api/comics.[id].ts": {
    id: "routes/api/comics.[id]";
    page: "/api/comics/:id";
  };
  "routes/api/chapters.[id].ts": {
    id: "routes/api/chapters.[id]";
    page: "/api/chapters/:id";
  };
  "routes/api/users.ts": {
    id: "routes/api/users";
    page: "/api/users";
  };
  "routes/api/upload.ts": {
    id: "routes/api/upload";
    page: "/api/upload";
  };
  "routes/api/auth.ts": {
    id: "routes/api/auth";
    page: "/api/auth";
  };
  "routes/api/purchase.ts": {
    id: "routes/api/purchase";
    page: "/api/purchase";
  };
};