// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/comics": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/api/comics": {
    params: {};
  };
  "/api/comics/:id": {
    params: {
      "id": string;
    };
  };
  "/api/chapters/:id": {
    params: {
      "id": string;
    };
  };
  "/api/users": {
    params: {};
  };
  "/api/upload": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin/dashboard" | "/admin/comics" | "/admin/users" | "/admin/analytics" | "/api/comics" | "/api/comics/:id" | "/api/chapters/:id" | "/api/users" | "/api/upload";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/comics.tsx": {
    id: "routes/admin/comics";
    page: "/admin/comics";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/analytics.tsx": {
    id: "routes/admin/analytics";
    page: "/admin/analytics";
  };
  "routes/api/comics.ts": {
    id: "routes/api/comics";
    page: "/api/comics";
  };
  "routes/api/comics.[id].ts": {
    id: "routes/api/comics.[id]";
    page: "/api/comics/:id";
  };
  "routes/api/chapters.[id].ts": {
    id: "routes/api/chapters.[id]";
    page: "/api/chapters/:id";
  };
  "routes/api/users.ts": {
    id: "routes/api/users";
    page: "/api/users";
  };
  "routes/api/upload.ts": {
    id: "routes/api/upload";
    page: "/api/upload";
  };
};