name = "comic-admin"
pages_build_output_dir = "build/client"
compatibility_date = "2024-01-01"

# 默认 D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "comic-dev"
database_id = "ce2df114-db14-4b26-8e28-82f5c9fa2e25"

[env.production]
name = "comic-admin"

[env.preview]
name = "comic-admin-preview"

# 环境变量
[env.production.vars]
NODE_ENV = "production"
JWT_SECRET = "your-production-jwt-secret"

[env.preview.vars]
NODE_ENV = "preview"
JWT_SECRET = "your-preview-jwt-secret"

# D1数据库
[[env.production.d1_databases]]
binding = "DB"
database_name = "comic-dev"
database_id = "ce2df114-db14-4b26-8e28-82f5c9fa2e25"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "comic-dev"
database_id = "ce2df114-db14-4b26-8e28-82f5c9fa2e25"

# R2存储
[[env.production.r2_buckets]]
binding = "FILES"
bucket_name = "comic-files-prod"

[[env.preview.r2_buckets]]
binding = "FILES"
bucket_name = "comic-files-preview"